# Generated by Django 4.1 on 2023-09-13 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "authors"},
        ),
    ]
